### PR TITLE
Update modal.js

### PR DESCRIPTION
**Pull request by manchumahara**
updating the text "Close" as translation " aut0poietic_iframe_modal_l10n.close_label"

### CODE REVIEW

**Comment by aut0poietic** [comment]
Hey! Morning @manchumahara --

Wanted to discuss this with you. I'm not sure this change is a good idea. 

The [original line ](https://github.com/aut0poietic/wp-admin-modal-example/blob/master/modal-iframe/js/modal.js#L16)uses a non-dynamic string so that if the `window.aut0poietic_iframe_modal_l10n` object is not populated for some reason, the button doesn't read `undefined`.

[The `if` statement on line 18 ](https://github.com/aut0poietic/wp-admin-modal-example/blob/master/modal-iframe/js/modal.js#L18)then checks for the presence of `window.aut0poietic_iframe_modal_l10n` and updates the value of the title and a11y text on the following lines.

Is the block at line 18 failing in your testing?

**Comment by manchumahara** [comment]
if that js file is loaded then aut0poietic_iframe_modal_l10n  will be an object for sure as , even you don't need to access it via window. aut0poietic_iframe_modal_l10n  because if modal.js is loaded  then aut0poietic_iframe_modal_l10n should be an object because this object is available in dom before the modal.js is loaded.

**Comment by manchumahara** [comment]
it seems I we notice, we don't need this section

```
if( typeof window.aut0poietic_iframe_modal_l10n === 'object' ) {
            $dialogHTML.find( '.iframe_modal-close' ).attr( 'title' , aut0poietic_iframe_modal_l10n.close_label ) ;
            $dialogHTML.find( '.iframe_modal-icon' ).text( aut0poietic_iframe_modal_l10n.close_label ) ;
        }

```

because the right way to add localisation string as object with the enqueue of js is 

wp_enqueue_style( 'iframe_modal' , $base . 'css/modal.css' );
wp_register_script( 'iframe_modal' , $base . 'js/modal.js' , array( 'jquery' ) ); //at first register it
                //now add the localize script with the same handle(here it is iframe_modal) of main js
                wp_localize_script(
                    'iframe_modal' ,
                    'aut0poietic_iframe_modal_l10n',
                    array(
                        "close_label" => __( 'Close Dialog' , 'iframe_modal' )
                    )
                );

now enqueue

wp_enqueue_script( 'iframe_modal');// this confirms that aut0poietic_iframe_modal_l10n  will be an object always in modal.js as wp_localize_script loads before wp_enqueue_script  if added with same handle or id of the js, here the handle or id is 'iframe_modal'

I think now you can make the actual change or I can send pull request again.

**Comment by aut0poietic** [comment]
> if that js file is loaded then aut0poietic_iframe_modal_l10n will be an object for sure as , even you don't need to access it via window. 

I disagree with both statements. 

As far as referencing global variables through the `window` object, I don't mind typing a few extra characters if it makes the object's scope explicit. 

As far as the the l10n object goes: Software breaks, people make mistakes typing in variable names and sometimes l10n objects aren't populated as expected. It happens. 

The way the script currently works, the dialog is populated with default (English) then updated if the l10n object exists. I'm also updating the labels with jQuery's`text()` and `attr()` methods. If I remember right, both escape the strings before insertion. 

Using string concatenation can potentially lead to situations where the button's label will read as `undefined`. Also, the concatenation occurs in the middle of a very long string, and difficult to see. As this is example code, I will always err on the side of clarity. 

I appreciate the request and the discussion!

**Comment by manchumahara** [comment]
Hi,

technically I don't find any situation if every thing is added properly I10 object can be undefined and typing variable name wrong is not a good logic as any programmer can type any thing wrong any where, this is why we see error logs, debug and fix,

Thanks, it's up to you. I am using this for one of my project and useful to me and I am modifying as my need and thought to add here too.  none of my changes broke my plugin as I am sure what I am doing.

**Pull request closed without merging**
